#!/usr/bin/env python3
"""
Export batch attribution outputs to a Markdown report.

Inputs:
- summary.json
- batch_results.jsonl

Output:
- report.md
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert attribution batch outputs into markdown report."
    )
    parser.add_argument(
        "--summary_file",
        type=str,
        default="artifacts/attribution_batch/summary.json",
        help="Path to summary.json generated by run_batch_attribution_modal.py",
    )
    parser.add_argument(
        "--results_file",
        type=str,
        default="artifacts/attribution_batch/batch_results.jsonl",
        help="Path to batch_results.jsonl generated by run_batch_attribution_modal.py",
    )
    parser.add_argument(
        "--output_file",
        type=str,
        default="artifacts/attribution_batch/report.md",
        help="Output markdown report path",
    )
    parser.add_argument(
        "--top_k_examples",
        type=int,
        default=10,
        help="How many top-attribution examples to include",
    )
    parser.add_argument(
        "--max_text_len",
        type=int,
        default=180,
        help="Max chars to show for each text field",
    )
    return parser.parse_args()


def load_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def load_jsonl(path: Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def truncate_text(s: str, max_len: int) -> str:
    if len(s) <= max_len:
        return s
    return s[: max(0, max_len - 3)] + "..."


def _fmt(v: Any, digits: int = 4) -> str:
    if isinstance(v, float):
        return f"{v:.{digits}f}"
    return str(v)


def build_overview_section(summary: Dict[str, Any]) -> List[str]:
    lines = ["## Overview", ""]
    lines.append("| Metric | Value |")
    lines.append("|---|---:|")
    lines.append(f"| total_examples | {_fmt(summary.get('total_examples', 0), 0)} |")
    lines.append(f"| ok_examples | {_fmt(summary.get('ok_examples', 0), 0)} |")
    lines.append(f"| failed_examples | {_fmt(summary.get('failed_examples', 0), 0)} |")
    lines.append(f"| ok_rate | {_fmt(summary.get('ok_rate', 0.0))} |")
    lines.append(
        f"| labeled_examples | {_fmt(summary.get('labeled_examples', 0), 0)} |"
    )

    acc = summary.get("accuracy")
    macro_f1 = summary.get("macro_f1")
    lines.append(f"| accuracy | {_fmt(acc) if acc is not None else 'N/A'} |")
    lines.append(f"| macro_f1 | {_fmt(macro_f1) if macro_f1 is not None else 'N/A'} |")
    lines.append(
        f"| mean_top_sentence_score | {_fmt(summary.get('mean_top_sentence_score', 0.0))} |"
    )
    lines.append(
        f"| mean_elapsed_seconds | {_fmt(summary.get('mean_elapsed_seconds', 0.0))} |"
    )
    lines.append("")
    return lines


def build_per_label_section(summary: Dict[str, Any]) -> List[str]:
    per_label = summary.get("per_label", {}) or {}
    if not per_label:
        return ["## Per-Label Metrics", "", "No labeled evaluation metrics available.", ""]

    lines = ["## Per-Label Metrics", ""]
    lines.append("| Label | Precision | Recall | F1 | Support |")
    lines.append("|---|---:|---:|---:|---:|")
    for label in ["impolite", "neutral", "polite"]:
        m = per_label.get(label)
        if not m:
            continue
        lines.append(
            "| "
            f"{label} | {_fmt(m.get('precision', 0.0))} | {_fmt(m.get('recall', 0.0))} | "
            f"{_fmt(m.get('f1', 0.0))} | {_fmt(m.get('support', 0), 0)} |"
        )
    lines.append("")
    return lines


def build_confusion_section(summary: Dict[str, Any]) -> List[str]:
    cm = summary.get("confusion_matrix", {}) or {}
    if not cm:
        return ["## Confusion Matrix", "", "No confusion matrix available.", ""]

    labels = ["impolite", "neutral", "polite"]
    lines = ["## Confusion Matrix", ""]
    lines.append("Rows = true labels, columns = predicted labels.")
    lines.append("")
    lines.append("| true \\ pred | impolite | neutral | polite |")
    lines.append("|---|---:|---:|---:|")
    for t in labels:
        row = cm.get(t, {})
        lines.append(
            f"| {t} | {int(row.get('impolite', 0))} | {int(row.get('neutral', 0))} | {int(row.get('polite', 0))} |"
        )
    lines.append("")
    return lines


def build_top_examples_section(
    records: List[Dict[str, Any]],
    top_k: int,
    max_text_len: int,
) -> List[str]:
    ok_records = [r for r in records if r.get("ok")]
    scored = []
    for rec in ok_records:
        sentences = rec.get("result", {}).get("sentences", [])
        if not sentences:
            continue
        top_sent = sentences[0]
        score = float(top_sent.get("attribution_score", 0.0))
        scored.append((score, rec, top_sent))
    scored.sort(key=lambda x: x[0], reverse=True)

    lines = ["## Top Attribution Examples", ""]
    if not scored:
        lines.append("No successful attribution examples found.")
        lines.append("")
        return lines

    lines.append(
        "| # | True | Pred | TopScore | TopSentence | InputText |"
    )
    lines.append("|---:|---|---|---:|---|---|")

    for idx, (score, rec, top_sent) in enumerate(scored[: max(0, top_k)], start=1):
        true_label = rec.get("true_label", "N/A") or "N/A"
        pred_label = (
            rec.get("result", {})
            .get("baseline_prediction", {})
            .get("label", "N/A")
        )
        top_sentence = truncate_text(str(top_sent.get("sentence", "")), max_text_len)
        input_text = truncate_text(str(rec.get("text", "")), max_text_len)
        lines.append(
            "| "
            f"{idx} | {true_label} | {pred_label} | {_fmt(score)} | "
            f"{top_sentence.replace('|', ' ')} | {input_text.replace('|', ' ')} |"
        )
    lines.append("")
    return lines


def build_footer(summary: Dict[str, Any]) -> List[str]:
    lines = ["## Run Config", ""]
    cfg_keys = [
        "input_file",
        "model_path",
        "use_large_model",
        "use_quantization",
        "num_ablations",
        "context_keep_prob",
        "min_context_sentences",
        "max_length",
        "chunk_size",
        "label_column",
    ]
    lines.append("| Key | Value |")
    lines.append("|---|---|")
    for k in cfg_keys:
        if k in summary:
            lines.append(f"| {k} | {summary[k]} |")
    lines.append("")
    return lines


def main() -> None:
    args = parse_args()
    summary_path = Path(args.summary_file)
    results_path = Path(args.results_file)
    output_path = Path(args.output_file)

    if not summary_path.exists():
        raise FileNotFoundError(f"summary file not found: {summary_path}")
    if not results_path.exists():
        raise FileNotFoundError(f"results file not found: {results_path}")

    summary = load_json(summary_path)
    records = load_jsonl(results_path)

    report_lines: List[str] = []
    report_lines.append("# Batch Attribution Report")
    report_lines.append("")
    report_lines.extend(build_overview_section(summary))
    report_lines.extend(build_per_label_section(summary))
    report_lines.extend(build_confusion_section(summary))
    report_lines.extend(
        build_top_examples_section(
            records=records,
            top_k=args.top_k_examples,
            max_text_len=args.max_text_len,
        )
    )
    report_lines.extend(build_footer(summary))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as f:
        f.write("\n".join(report_lines))

    print(f"Saved markdown report: {output_path}")


if __name__ == "__main__":
    main()

